Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.hostname = "k3s-node"
  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provider "virtualbox" do |vb|
    vb.name   = "k3s-node"
    vb.memory = "3048"
    vb.cpus   = 4
  end

  config.vm.box_check_update = false
end