Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.hostname = "monitoring-node"
  config.vm.network "private_network", ip: "192.168.56.11"

  config.vm.provider "virtualbox" do |vb|
    vb.name   = "monitoring-node"
    vb.memory = "2048"
    vb.cpus   = 2
  end

  config.vm.box_check_update = false
end